sudo: required
services:
    - docker

before_install:
    - docker build -t konsta2106/react-test -f ./client/Dockerfile.dev ./client

script:
    # Run react test and exit them
    - docker run konsta2106/react-test npm test -- --coverage

after_success:
    - docker build -t konsta2106/multi-client ./client
    - docker build -t konsta2106/multi-nginx ./nginx
    - docker build -t konsta2106/multi-calculator ./calculator
    - docker build -t konsta2106/multi-server ./server
    
    # Login to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Push images to docker hub
    - docker push konsta2106/multi-nginx
    - docker push konsta2106/multi-client
    - docker push konsta2106/multi-calculator
    - docker push konsta2106/multi-server

deploy:
    provider: elasticbeanstalk
    region: eu-west-3
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-3-721010426051
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
