version: "3"
services: 
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: postgres_password
        container_name: docker-postgres
        restart: always
    redis:
        image: redis:latest
        container_name: docker-redis
        restart: always
    api:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - /usr/src/app/node_modules
            - ./server:/usr/src/app
        container_name: docker-api
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        restart: always
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /usr/src/app/node_modules
            - ./client:/usr/src/app
        container_name: client
    calculator:
        build:
            dockerfile: Dockerfile.dev
            context: ./calculator
        volumes: 
            - /usr/src/app/node_modules
            - ./calculator:/usr/src/app
        container_name: calculator
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
        container_name: nginx